config/routes.rb
Rails.application.routes.draw do

  #activeadmin urls
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #items controller
  resources :items

  #users could sign up multiple times
  resources :users

  #users can only make one session
  resource :session


  get 'about', to: 'pages#about'
  root 'pages#home'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :title, presence: true
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

# make current_user avaiable to views
helper_method :current_user, :is_logged_in?

# run this on every single page and Action
before_action :current_user

  def current_user
    if is_logged_in?
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
    @current_user
  end

  def is_logged_in?
    session[:user_id].present?
  end

  def force_login
    unless is_logged_in?
      flash[:error] = 'You are not logged in'
      redirect_to root_path
    end
  end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

before_action :force_login

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # we dont need any variables here because we're not addingt o the database

  end


  def create
    @username = form_params[:username]
    @password = form_params[:password]

    @user = User.find_by(username: @username).try(:authenticate, @password)

    if @user.present?
      session[:user_id] = @user.id
      flash[:success] = 'You are now logged in!'
      redirect_to root_path
    else
      render "new"
    end
  end



  def destroy
    reset_session

    flash[:success] = 'You are now logged out!'

    redirect_to root_path

  end

  def form_params
    params.require(:session).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(form_params)

    # check if the user can save
    if @user.save
      # save the user id of that session
      session[:user_id] = @user.id

      #let the user know they signed up
      flash[:success] = "Welcome to Source!"

      redirect_to root_path
    else
      render 'new'
    end
  end

  def form_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<div class="item">
  <%= link_to item_path(item) do %>
    <h2><%= item.title %></h2>
    <%= image_tag item.image.medium.url %>
  <% end %>
</div>

app/views/items/index.html.erb
<h1>Photos</h1>

<%= render partial: 'item', collection: @items %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Source</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:success].present?%>
      <div class="success">
        <%= flash[:success]%>
      </div>
    <% end %>

    <% if flash[:error].present?%>
      <div class="error">
        <%= flash[:error]%>
      </div>
    <% end %>

    <header>
      <h1>Source</h1>
      <nav>
        <% if is_logged_in? %>
          <strong>Hi, <%= @current_user.username %></strong>
          <%= link_to 'Log Out', session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign Up', new_user_path %>
          <%= link_to 'Sign In', new_session_path %>
        <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Source Home page</h1>

<p>
  <%= link_to 'Sign Up', new_user_path, class: 'button'%>
  <%= link_to 'Log In', new_session_path, class: 'button-outline button'%>
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= simple_form_for @user do |f| %>

  <%= f.input :name %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit %>

<% end %>